install: true
script: echo "We don't need no tests."
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "www.refine.bio"
  skip_cleanup: true
  local_dir: public
  on:
    branch: master
